// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace booking_rest_api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("StatusId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2026, 5, 24, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = 1,
                            ClinicId = 1,
                            DoctorId = 1,
                            Duration = 30,
                            PatientId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2026, 5, 24, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = 1,
                            ClinicId = 1,
                            DoctorId = 1,
                            Duration = 30,
                            PatientId = 2,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2026, 5, 24, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = 1,
                            ClinicId = 1,
                            DoctorId = 1,
                            Duration = 30,
                            PatientId = 3,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "General Health Consultation"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Follow-up Consultation"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vaccination"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Medicine Prescription"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Emergency"
                        });
                });

            modelBuilder.Entity("Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oslo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stavanger"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bergen"
                        });
                });

            modelBuilder.Entity("Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Karl Johans gate 8",
                            CityId = 1,
                            Email = "oslo@klinikken.no",
                            Name = "Oslo Sentrum Klinikk",
                            Phone = "222522222",
                            PostalCode = "2232"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Maruksens gate 32",
                            CityId = 2,
                            Email = "stavanger@klinikken.no",
                            Name = "Stavanger Medisinske",
                            Phone = "522223233",
                            PostalCode = "5223"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Brygga 9",
                            CityId = 3,
                            Email = "bergen@klinikken.no",
                            Name = "Bergen Bryggen Klinikk",
                            Phone = "22525252",
                            PostalCode = "3232"
                        });
                });

            modelBuilder.Entity("Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("FirstName", "LastName")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            Email = "mb@klinikken.no",
                            FirstName = "Mathias",
                            LastName = "Bekkemellem",
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClinicId = 2,
                            Email = "cj@klinikken.no",
                            FirstName = "Carina",
                            LastName = "Johansen",
                            SpecialtyId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClinicId = 3,
                            Email = "jc@klinikken.no",
                            FirstName = "John",
                            LastName = "Carlsen",
                            SpecialtyId = 1
                        });
                });

            modelBuilder.Entity("Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NationalIdentityNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NationalIdentityNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1992, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mark.j@mail.com",
                            FirstName = "Mark",
                            IsRegistered = true,
                            LastName = "Johanson",
                            NationalIdentityNumber = "524231231",
                            PasswordHash = "FAKEHASH",
                            Phone = "24242424",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1991, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tobben@mail.com",
                            FirstName = "Tobias",
                            IsRegistered = true,
                            LastName = "Karevik",
                            NationalIdentityNumber = "66666666",
                            PasswordHash = "FAKEHASH",
                            Phone = "555555",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1982, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "danny@mail.com",
                            FirstName = "Daniela",
                            IsRegistered = true,
                            LastName = "Thomson",
                            NationalIdentityNumber = "878787878",
                            PasswordHash = "FAKEHASH",
                            Phone = "333222333",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1986, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carlos@mail.com",
                            FirstName = "Carlos",
                            IsRegistered = false,
                            LastName = "Rodriguez",
                            Phone = "777788877",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1984, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jandan@mail.com",
                            FirstName = "Jan",
                            IsRegistered = false,
                            LastName = "Dan",
                            Phone = "222777722",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "dev@dev.com",
                            FirstName = "Admin",
                            IsRegistered = false,
                            LastName = "Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEBoc7/xHyQ88YJ7b5/fvDDkFTAH6GmsiH03ouiYgQWUEx1zu7NsSDmTeHrcdsHHyxg==",
                            Phone = "99999999",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "General Health"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cardiologist"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dermatologist"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Peditrician"
                        });
                });

            modelBuilder.Entity("Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Patient"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Models.Appointment", b =>
                {
                    b.HasOne("Models.Category", "Category")
                        .WithMany("Appointments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Clinic", "Clinic")
                        .WithMany("Appointments")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Status", "Status")
                        .WithMany("Appointments")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Models.Clinic", b =>
                {
                    b.HasOne("Models.City", "City")
                        .WithMany("Clinics")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Models.Doctor", b =>
                {
                    b.HasOne("Models.Clinic", "Clinic")
                        .WithMany("Doctors")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Models.Patient", b =>
                {
                    b.HasOne("Role", "Role")
                        .WithMany("Patients")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Models.Category", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Models.City", b =>
                {
                    b.Navigation("Clinics");
                });

            modelBuilder.Entity("Models.Clinic", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Models.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Models.Status", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
