name: Build and deploy ASP.Net Core app to Azure Web App - medcare

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.x'
  PROJECT_PATH: 'backend'   

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ./published --no-restore

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./published

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_72C89B36B386408687DA4C60DB585E3F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_75D2FDC0D3F34E51BE302AC214ED1E8B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C9E10B570ADD48538F28F2D54554243E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'medcare'
          slot-name: 'Production'
          package: .
